theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
true-color = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[keys.normal]
"C-A-l" = ":theme solarized_light"
"C-A-d" = ":theme autumn"
"C-A-w" = ":set soft-wrap.enable true"
"C-A-q" = ":set soft-wrap.enable false"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
